name: Bleeding-Edge Build

on:
  push:
    branches: ['main']
    paths: ['src/**', '**/*.gradle', 'gradle.properties']


concurrency:
  group: auto-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      BLEEDING_EDGE: true
      CI: true
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Get Mod Name
        id: mod_name
        run: echo "modName=$(./gradlew -q printModName)" >> $GITHUB_OUTPUT

      - name: Get Mod Version
        id: ver
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Get the latest commit's hash.
        id: suffix
        run: echo "LATEST_COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c 1-7)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build --build-cache --stacktrace

      - name: Rename Jars
        run: for file in build/libs/*; do mv "$file" "${file/EDGE/EDGE-$(date --utc '+%Y%m%d-%H%M%S')-${{ env.LATEST_COMMIT_HASH}}}"; done;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*
          if-no-files-found: error
          retention-days: 90

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configuration: ./.github/json/config-bleedingedge.json
          fromTag: bleeding-edge
          toTag: refs/heads/main
          fetchViaCommits: true
          failOnError: false

      - name: Bleeding-Edge Release
        uses: andelf/nightly-release@46e2d5f80828ecc5c2c3c819eb31186a7cf2156c
        with:
          tag_name: bleeding-edge
          name: 'BleedingEdge-${{steps.ver.outputs.version}}-${{env.LATEST_COMMIT_HASH}}'
          prerelease: true
          body: |
            This is a **Bleeding-Edge** release of ${{steps.mod_name.outputs.modName}} (for Minecraft 1.20.1), that was generated by [this action run](https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}) upon ${{env.LATEST_COMMIT_HASH}} being pushed.
            
            **Bleeding-Edge releases are NOT meant for use outside of testing and bug-hunting, as things may be HEAVILY broken.**
            ***<ins>Your choice to use this build in your main world is your responsibility</ins>.***
            
            If you find any issues, please report them [here](https://github.com/${{ github.repository }}/issues).
            ${{ steps.changelog.outputs.changelog }}
          files: build/libs/*.jar